In [34]:
import pandas as pd
import sklearn
import nltk, string

from nltk.corpus import stopwords

stop_words = set([word.translate(str.maketrans('', '', string.punctuation))
                  for word in stopwords.words('english')])

sanitized_descriptions = []
for i in range(0,10000):
    with open('descriptions_train/%s.txt' % i) as f:
        descriptions = ' '.join(f.read().strip().split('\n'))
        descriptions = descriptions.translate(str.maketrans('', '', string.punctuation)).lower()
        all_words = descriptions.split(' ')
        all_words = ' '.join([a for a in all_words if a and a not in stop_words])
        sanitized_descriptions.append(all_words)
        
df = pd.DataFrame(sanitized_descriptions, columns=['sentence'])
df

                                               sentence
0     skateboarder putting show using picnic table s...
1     bowl soup carrots shrimp noodles healthy food ...
2     man walking across street busy intersection ic...
3     young boy throwing frisbee grassy field young ...
4     young child yard holding bat boy raring back b...
...                                                 ...
9995  man placing items pizza pan man cutting someth...
9996  woman standing bunch unripe bananas person loo...
9997  bunch paper covering walls bedroom bed sitting...
9998  silver train traveling past train stations pas...
9999  surfer hits wipe big wave man riding wave wate...

[10000 rows x 1 columns]

In [33]:
dictionary = {}
for sd in sanitized_descriptions:
    words = sd.split(' ')
    for w in words:
        dictionary[w] = dictionary.get(w, 0) + 1
        
dictionary = set(dictionary.keys())
len(dictionary)

9731

In [37]:
def vectorize(row):
    words = row['sentence'].split(' ') 
    for w in words:
        row[w] = row[w] + 1
    return row

features = pd.DataFrame(columns=dictionary)
new_combined = pd.concat([df, features], axis=1).fillna(0)
new_combined

,sentence,businesswear,balloons,outbuildings,count,luigi,boarding,site,pancakes,destinations,...,valentines,casually,chair,pot,fathers,unmowed,unbaked,urinals,entry,pricing
0,skateboarder putting show using picnic table s...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,bowl soup carrots shrimp noodles healthy food ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,man walking across street busy intersection ic...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,young boy throwing frisbee grassy field young ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,young child yard holding bat boy raring back b...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,man placing items pizza pan man cutting someth...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,woman standing bunch unripe bananas person loo...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,bunch paper covering walls bedroom bed sitting...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,silver train traveling past train stations pas...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,surfer hits wipe big wave man riding wave wate...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
new_combined = new_combined.apply(vectorize, axis=1)

In [46]:
new_combined.to_csv('bag_of_words.csv')